---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyr)
library(stringr)
library(lubridate)
library(data.table)
library(collapse)
library(ggplot2)
library(magrittr)

setDTthreads(threads = 0)
knitr::opts_knit$set(root.dir = "./class_datasets")
```

```{r}
RDS_files = grep(".rds", list.files(), value = TRUE)
data_list = RDS_files |>
  lapply(readRDS) |>
  lapply(as.data.table) |>
  setNames(gsub("(_data)?.rds", "", RDS_files))

cleaned_data_list = copy(data_list)
names(cleaned_data_list)
```

```{r}
head(cleaned_data_list[["laws_incentives"]])
```


```{r}
cleaned_data_list[["gasprice"]] = 
  cleaned_data_list[["gasprice"]] |>
  set(j = "date", value = NULL) |>
  ts(frequency = 12, start = c(2000, 6)) |>
  window(start = c(2012, 1), end = c(2022, 12)) |>
  aggregate(FUN = mean, na.rm = TRUE) |>
  t() |>
  as.data.table(keep.rownames = TRUE) |>
  setNames(c("state", paste0("avg_gasprice_", as.character(2012:2022))))
cleaned_data_list[["gasprice"]][, state := state.abb[match(state, gsub("[[:space:]]", "", tolower(state.name)))]]

head(cleaned_data_list[["gasprice"]])
```

```{r}
cleaned_data_list[["climate_attitudes"]][, (5:19) := lapply(.SD, as.numeric), .SDcols = -c(1:4)]
cleaned_data_list[["climate_attitudes"]][, state := state.abb[match(trimws(State), state.name)]]
cleaned_data_list[["climate_attitudes"]][, c("STATEFP", "COUNTYFP") := GEOID |>
                                           str_pad(5, pad = "0") |>
                                           substring(first = c(1,3), last = c(2,5)) |>
                                           as.list(), by = GEOID]
cleaned_data_list[["climate_attitudes"]][, c("GEOID", "State", "County", "GeoName") := NULL]
cleaned_data_list[["climate_attitudes"]] = na.omit(cleaned_data_list[["climate_attitudes"]], "state")

head(cleaned_data_list[["climate_attitudes"]])
```

```{r}
cleaned_data_list[["election"]] = as.data.table(readRDS("election_data.rds"))

cleaned_data_list[["election"]][, `:=`(proportion = candidatevotes/totalvotes,
                                       party = substring(tolower(party), 1, 3))]

cleaned_data_list[["election"]][, c("STATEFP", "COUNTYFP") := county_fips |>
                                           str_pad(5, pad = "0") |>
                                           substring(first = c(1,3), last = c(2,5)) |>
                                           as.list(), by = county_fips]

cleaned_data_list[["election"]] = cleaned_data_list[["election"]] |>
  subset(party == "dem") |>
  set(j = c("state", "county_name", "county_fips", "party", "candidatevotes", "totalvotes"), value = NULL) |>
  dplyr::distinct() |>
  na.omit() |>
  dcast(... ~ year, value.var = "proportion", sep = "_dem_proportion", fun.aggregate = sum) |>
  setnames(old = c("state_po", "2016", "2020"), new = c("state", "2016_dem_proportion", "2020_dem_proportion"))

head(cleaned_data_list[["election"]])
```


```{r}
cleaned_data_list[["road_milage"]] = cleaned_data_list[["road_milage"]][, GEOID := str_pad(GEOID, 11, pad = "0")]
  
head(cleaned_data_list[["road_milage"]])
```

```{r}
cleaned_data_list[["rest_stops"]] = na.omit(cleaned_data_list[["rest_stops"]][, GEOID := str_pad(GEOID, 11, pad = "0")])

head(cleaned_data_list[["rest_stops"]])
```

```{r}
top_50_categories = cleaned_data_list[["POI_counts"]][, colSums(.SD, na.rm = TRUE), .SDcols = -"GEOID"] |>
  sort() |>
  rev() |>
  names() |>
  head(50)

cleaned_data_list[["POI_counts"]] = cleaned_data_list[["POI_counts"]][, .SD, .SDcols = c("GEOID", top_50_categories)]

head(cleaned_data_list[["POI_counts"]])
```

```{r}
lat_long_geoid = as.data.table(readRDS("EVstations_coord_GEOID.rds"))

cleaned_data_list[["EVstations"]][, GEOID := lat_long_geoid$GEOID]
cleaned_data_list[["EVstations"]] =
  cleaned_data_list[["EVstations"]][!is.na(GEOID), c(.N, lapply(.SD, sum, na.rm = TRUE)), by=GEOID, .SDcols = 18:20]
cleaned_data_list[["EVstations"]][, `:=`(N_Stations = N, N = NULL)]
```


```{r}
state_merged_data = merge(cleaned_data_list$laws_incentives, cleaned_data_list$gasprice, by = "state", all = TRUE)
state_merged_data = merge(state_merged_data, cleaned_data_list$climate_attitudes, by = "state", all = TRUE)
state_merged_data = merge(state_merged_data, cleaned_data_list$election, by = c("state", "STATEFP", "COUNTYFP"), all = TRUE)

GEOID_merged_data = merge(cleaned_data_list$rest_stops, cleaned_data_list$road_milage, by = "GEOID", all = TRUE)
GEOID_merged_data = merge(GEOID_merged_data, cleaned_data_list$POI_counts, by = "GEOID", all = TRUE)

merged_data = merge(cleaned_data_list$census, cleaned_data_list$EVstations, by = "GEOID", all.x = TRUE)
merged_data = merge(merged_data, GEOID_merged_data, by = "GEOID", all.x = TRUE)
merged_data = merge(merged_data, state_merged_data, by =  c("state", "STATEFP", "COUNTYFP"), all.x = TRUE)
merged_data = unique(merged_data, by = "GEOID")
```

```{r}
saveRDS(merged_data, "../merged_data.rds", compress = "xz")
fwrite(merged_data, "../merged_data.csv")
```