---
title: "R Notebook"
html_notebook: default
---

```{r setup, include=FALSE}
library(tidyr)
library(stringr)
library(magrittr)
library(lubridate)
library(data.table)
library(collapse)
library(ggplot2)
library(knitr)
library(here)

here::i_am(".git/config")
here::here("data_aggregate", "class_datasets") %>%
  knitr::opts_chunk$set("root.dir" = .)
setDTthreads(threads = 0)

state.name = c(state.name, "District of Columbia")
state.abb = c(state.abb, "DC")

formals(merge.data.table)$all = TRUE
merge = merge.data.table
```

```{r, warning=FALSE}
setwd(knitr::opts_chunk$get("root.dir"))
CSV_files = grep(".csv", list.files(), value = TRUE)
data_list = CSV_files |>
  lapply(fread) |>
  setNames(gsub("(_data)?.csv", "", CSV_files))

cleaned_data_list = copy(data_list)
names(cleaned_data_list)
```

```{r}
head(cleaned_data_list[["laws_incentives"]])
```

```{r}
cleaned_data_list[["gasprice"]] = 
  cleaned_data_list[["gasprice"]] |>
  set(j = "date", value = NULL) |>
  ts(frequency = 12, start = c(2000, 6)) |>
  window(start = c(2012, 1), end = c(2022, 12)) |>
  aggregate(FUN = mean, na.rm = TRUE) |>
  t() |>
  as.data.table(keep.rownames = TRUE) |>
  setNames(c("state", paste0("avg_gasprice_", as.character(2012:2022))))
cleaned_data_list[["gasprice"]][, state := state.abb[match(state, gsub("[[:space:]]", "", tolower(state.name)))]]

head(cleaned_data_list[["gasprice"]])
```

```{r}
cleaned_data_list[["climate_attitudes"]][, (5:19) := lapply(.SD, as.numeric), .SDcols = -c(1:4)]
cleaned_data_list[["climate_attitudes"]][, state := state.abb[match(trimws(State), c(state.name))]]
cleaned_data_list[["climate_attitudes"]][, c("STATEFP", "COUNTYFP") := GEOID |>
                                           str_pad(5, pad = "0") |>
                                           substring(first = c(1,3), last = c(2,5)) |>
                                           as.integer() |>
                                           as.list(), by = GEOID]
cleaned_data_list[["climate_attitudes"]][, c("GEOID", "State", "County", "GeoName") := NULL]
cleaned_data_list[["climate_attitudes"]] = unique(cleaned_data_list[["climate_attitudes"]], by = c("STATEFP", "COUNTYFP"), fromLast = TRUE)

head(cleaned_data_list[["climate_attitudes"]])
```

```{r}
cleaned_data_list[["election"]][, `:=`(proportion = candidatevotes/totalvotes,
                                       party = substring(tolower(party), 1, 3))]

cleaned_data_list[["election"]][, c("STATEFP", "COUNTYFP") := county_fips |>
                                  str_pad(5, pad = "0") |>
                                  substring(first = c(1,3), last = c(2,5)) |>
                                  as.integer() |>
                                  as.list(), by = county_fips]

cleaned_data_list[["election"]] = cleaned_data_list[["election"]] |>
  subset(party == "dem") |>
  set(j = c("state", "county_name", "county_fips", "party", "candidatevotes", "totalvotes"), value = NULL) |>
  dplyr::distinct() |>
  na.omit() |>
  dcast(... ~ year, value.var = "proportion", sep = "_dem_proportion", fun.aggregate = sum) |>
  setnames(old = c("state_po", "2016", "2020"), new = c("state", "2016_dem_proportion", "2020_dem_proportion"))

head(cleaned_data_list[["election"]])
```

```{r}
head(cleaned_data_list[["road_mileage"]])
```

```{r}
head(cleaned_data_list[["rest_stops"]])
```

```{r}
top_50_categories = cleaned_data_list[["POI_counts"]][, colSums(.SD, na.rm = TRUE), .SDcols = -"GEOID"] |>
  sort() |>
  rev() |>
  names() |>
  head(50)

cleaned_data_list[["POI_counts"]] = cleaned_data_list[["POI_counts"]][, .SD, .SDcols = c("GEOID", top_50_categories)]

head(cleaned_data_list[["POI_counts"]])
```

```{r}
cleaned_data_list[["EVstations"]] = with(cleaned_data_list, EVstations[EVstations_coord_GEOID, on = .NATURAL])
cleaned_data_list[["EVstations"]] = cleaned_data_list[["EVstations"]][!is.na(GEOID), c(.N, lapply(.SD, sum, na.rm = TRUE)), by=GEOID, .SDcols = 18:20] |> setnames("N", "N.Stations")
```

```{r}
merged_data = with(cleaned_data_list, {
  
  state_merged_data = Reduce(merge, list(laws_incentives, gasprice))
  county_merged_data = Reduce(merge, list(election, climate_attitudes))
  GEOID_merged_data = Reduce(merge, list(POI_counts, road_mileage, rest_stops))
  
  state_merged_data[
    county_merged_data[
      GEOID_merged_data[
        EVstations[census, on = .NATURAL] |> replace_NA(value = 0, cols = names(EVstations)),
      on = "GEOID"],
    on = c("state", "STATEFP", "COUNTYFP")],
  on = "state"] 

})

merged_data[, `:=`(STATEFP = str_pad(STATEFP, 2, pad = 0),
                   COUNTYFP = str_pad(COUNTYFP, 3, pad = 0),
                   TRACTCE = str_pad(TRACTCE, 6, pad = 0),
                   GEOID = str_pad(GEOID, 11, pad = 0))] |>
  setcolorder(c("GEOID", "state", "STATEFP", "COUNTYFP", "TRACTCE"))

head(merged_data)
```

```{r}
fwrite(merged_data, "../merged_data.csv")
```
